### ISSUE TITLE
No issue but request

### ISSUE THREAD

**Issue by 7ElyGorilla** [Stealerium/Stealerium#153]
Could you pls add telegram support and for telegram instead of using a third party can you make it send just the zip

**Comment by kgnfth** [comment]
Lets do it.

**Comment by 7ElyGorilla** [comment]
nice so w from you

**Comment by kgnfth** [comment]
Done checkout commit 5e4bb19 and the build [Build_2024.09.28_21-05](https://github.com/Stealerium/Stealerium/releases/tag/Build_2024.09.28_21-05)

**Comment by kgnfth** [comment]
By the way, you requested to upload the zip file directly to Telegram along with the report, but that won’t work because keyloggers won’t be included. Once a file is uploaded via Telegram using the sendDocument method, it can't be edited afterward, unlike text messages, which can be modified. Telegram allows editing of text messages, but not documents, photos, or other media files once they’re sent. That’s why we still use GofileService for file uploads.

If u encounter issues with Gofile let me know.
